name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          set -eux
          npm install

      - name: Build
        run: |
          set -eux
          npm run build

      - name: Lint
        run: |
          set -eux
          npm
          npm run lint:check

      - name: Run tests
        run: |
          set -eux
          npm t
